# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ef0fU0K3nbmX8nx88-3nXu8PyjwN4_s
"""

import streamlit as st
import zipfile
import random
import os

# セッション状態を初期化
if "questions" not in st.session_state:
    st.session_state.questions = []
if "current_q" not in st.session_state:
    st.session_state.current_q = 0
if "score" not in st.session_state:
    st.session_state.score = 0

uploaded_file = st.file_uploader("曲データのZIPをアップロードしてください", type="zip")

if uploaded_file and not st.session_state.questions:
    with zipfile.ZipFile(uploaded_file, "r") as z:
        wav_files = [f for f in z.namelist() if f.endswith(".wav")]
        random.shuffle(wav_files)
        # 最大100問に制限
        st.session_state.questions = wav_files[:100]

if st.session_state.questions:
    current_idx = st.session_state.current_q
    chosen_file = st.session_state.questions[current_idx]

    with zipfile.ZipFile(uploaded_file, "r") as z:
        with z.open(chosen_file) as f:
            audio_bytes = f.read()

    # 音声再生（1回だけ流す）
    st.audio(audio_bytes, format="audio/wav")

    correct_title = os.path.splitext(os.path.basename(chosen_file))[0]
    st.write(f"ヒント: {len(correct_title)}文字")

    answer = st.text_input("曲名をひらがなで入力", key=f"answer_{current_idx}")

    if st.button("回答する"):
        if answer == correct_title:
            st.success("正解！")
            st.session_state.score += 1
        else:
            st.error(f"不正解！ 正解は {correct_title}")

        # 次の問題へ
        st.session_state.current_q += 1

        # 全部終わったら結果表示
        if st.session_state.current_q >= len(st.session_state.questions):
            st.write("🎉 クイズ終了！")
            st.write(f"スコア: {st.session_state.score} / {len(st.session_state.questions)}")
            st.session_state.current_q = 0
            st.session_state.questions = []