# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ef0fU0K3nbmX8nx88-3nXu8PyjwN4_s
"""

import streamlit as st
import zipfile
import io
import random
import re

# ヒント生成関数
def generate_hint(answer: str) -> str:
    hint = ""
    for char in answer:
        if char.isalpha() or ('ぁ' <= char <= 'ん') or ('ァ' <= char <= 'ン') or ('一' <= char <= '龥'):
            hint += "〇"
        elif char == " ":
            hint += "□"
        else:
            hint += char
    return hint

# ファイル名から答えを抽出（例：001_めざせポケモンマスター.mp3 → めざせポケモンマスター）
def extract_answer(filename: str) -> str:
    name = filename.rsplit("/", 1)[-1]  # ZIP内のパスを除去
    name = name.rsplit(".", 1)[0]       # 拡張子を除去
    parts = name.split("_", 1)
    return parts[1] if len(parts) == 2 else parts[0]

# セッション状態の初期化
if "questions" not in st.session_state:
    st.session_state.questions = []
if "current_q" not in st.session_state:
    st.session_state.current_q = 0
if "score" not in st.session_state:
    st.session_state.score = 0

# タイトルと説明
st.title("🎮 アニソンクイズ（ファイル名ベース）")
st.markdown("""
#### 📝 説明
- 曲の一部が流れます。
- **ひらがな、アルファベットの小文字**で回答してください。
- **スペース（□）、ドット、記号**はヒントとして表示されます。
- **200問以上の中からランダムで100問**出題されます。
- 問題は**一度しか流れません**。
- 出題基準は「**インターネットを見ていれば回答できる**」です。
- 音量が一定でないので、**音量の上げすぎにはご注意ください**。
""")

# ZIPファイルアップロード
uploaded_zip = st.file_uploader("🎵 MP3入りZIPファイルをアップロード", type="zip")

if uploaded_zip and not st.session_state.questions:
    with zipfile.ZipFile(uploaded_zip) as z:
        mp3_files = sorted([f for f in z.namelist() if f.endswith(".mp3")])
        random.shuffle(mp3_files)
        st.session_state.questions = mp3_files[:100]

if st.session_state.questions:
    current_idx = st.session_state.current_q
    mp3_file = st.session_state.questions[current_idx]

    with zipfile.ZipFile(uploaded_zip) as z:
        mp3_data = z.read(mp3_file)
        correct_answer = extract_answer(mp3_file).strip()

    st.subheader(f"🎵 第 {current_idx + 1} 問")
    st.audio(mp3_data, format="audio/mp3")
    st.write("🔍 ヒント：" + generate_hint(correct_answer))

    user_input = st.text_input("答えを入力（ひらがな・英小文字）", key=f"answer_{current_idx}")

    if st.button("回答する"):
        if user_input.strip() == correct_answer:
            st.success("🎉 正解！")
            st.session_state.score += 1
        else:
            st.error(f"❌ 不正解… 正解は「{correct_answer}」でした")

        st.session_state.current_q += 1

        if st.session_state.current_q >= len(st.session_state.questions):
            st.markdown("---")
            st.header("🏁 クイズ終了！")
            st.write(f"あなたのスコア：**{st.session_state.score} / {len(st.session_state.questions)}**")
            st.balloons()
            # リセット
            st.session_state.questions = []
            st.session_state.current_q = 0
            st.session_state.score = 0